In [1]:
import numpy as np

In [2]:
numbers_array = np.array([1,2,3,4,5])

numbers_array

array([1, 2, 3, 4, 5])

In [3]:
vector = np.array([1,2,3,4,5])

In [5]:
vector.ndim #this is a one dimensional array (which is also called a vector)

1

In [7]:
vector.size # this shows the number of elements in a vector

5

In [9]:
vector.shape #indicates the size of each dimension in a vector. THis si saying that we have 5 elements and there is only one row

(5,)

In [13]:
matrix = np.array([[1,2,3], 
                  [4,5,6]])

In [16]:
matrix.ndim #this is a two dimensional matrix

2

In [18]:
matrix.size # here we see that we have six elements in a matrix

6

In [24]:
matrix.shape # we have two rows, and 3 columns.

(2, 3)

In [22]:
np.zeros([2,3]) # this covers all of our elements with the value 0. it makes 2 rows, with 3 elements each.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.arange(1,10,2) #start at 1, go to 10, but skip by 2

array([1, 3, 5, 7, 9])

In [29]:
np.random.randint(1,10,5) # the low value we want is 1, the high value we want is 10, and we want 5 random numbers.

array([9, 1, 9, 2, 3])

In [ ]:
np.random.seed(1) # setting a seed allows us to make our results reproduceable. So our randomzied process becomes fixed.
np.random.randint(1,10,5)

array([2, 8, 7, 3, 5])

In [33]:
np.repeat(10, 5) #repeat a number 5 times

array([10, 10, 10, 10, 10])

In [35]:
np.tile(vector, 2) # this repeats a whole array a specified amount of times.

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [36]:
rng = np.random.default_rng() # this is a random number generator

In [37]:
rng.normal(0, 1, 10) #this ensures the dummy data we pull has a mean of 0 and a standard deviation of 1. THis is normal distribuion.

array([-0.71212307, -0.1129138 ,  1.10607984, -0.61677031, -0.91487052,
        0.50473295,  0.27035965, -0.53012773,  0.64880746, -1.39014943])

In [39]:
matrix.T #This transposes the elements. changes from 2 rows 3 columns, to 3 rows 2 colums.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
matrix.reshape(6,1) #6 rows, 1 col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6])

In [43]:
matrix1 = np.array([[1,2,3], [4,5,6]])

In [44]:
matrix2 = np.array([[7,8,9], [10,11,12]])

In [49]:
np.vstack((matrix1, matrix2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
np.hstack((matrix1, matrix2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
#arrays also make it easy to do math. See the this

matrix + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [53]:
matrix *2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [54]:
matrix2 - matrix1

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
#we can also summarize values in an array. 

matrix1.sum()

np.int64(6)

In [61]:
matrix1.max()

np.int64(6)

In [60]:
matrix1.mean()

np.float64(3.5)

In [ ]:
matrix1.mean(axis = 0)

#axis 0 = columns
#axis 1 = rows

array([2.5, 3.5, 4.5])

In [65]:
matrix1.mean(axis = 1) # the first row gives us an average of 2, and the second gives 5.

array([2., 5.])

In [67]:
# we can also pull out specific columns or rows in a matrix. 

matrix1[0,:]

array([1, 2, 3])

In [68]:
matrix1[:,0]

array([1, 4])

In [70]:
matrix1[:,1]

array([2, 5])

In [ ]:
# we can also evaluate if each matrix element is divisible by a number

matrix2 % 3 == 0

# this gives us a bunch of boolean values

array([[False, False,  True],
       [False, False,  True]])

In [73]:
# we can also ask numpy to retrun items that only meet the criteria

matrix2[matrix2 % 3 == 0]

array([ 9, 12])

In [ ]:
#this function is faster than a for loop. If this condition is met, return the element, or else return a 0.

np.where(matrix2 % 3 == 0,
    matrix2,
    0)

array([[ 0,  0,  9],
       [ 0,  0, 12]])

# Exercise 1

In [82]:
ex1 = np.arange(1, 21,1)
ex1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [84]:
ex1.mean()

np.float64(10.5)

In [85]:
ex1.sum()

np.int64(210)

In [87]:
ex1.std()

np.float64(5.766281297335398)

# Exercise 2

In [88]:
arr = np.array([[2, 7, 12], [4,15,3], [8,1,20]])

In [89]:
arr

array([[ 2,  7, 12],
       [ 4, 15,  3],
       [ 8,  1, 20]])

In [ ]:
arr[arr > 10] # this return everything that is greater than 10

array([12, 15, 20])

In [91]:
np.where (arr < 5,
          0, 
          arr)

array([[ 0,  7, 12],
       [ 0, 15,  0],
       [ 8,  0, 20]])

# Exercise 3

In [ ]:
print(arr[:,0]) # printing the first column

[2 4 8]

In [108]:
print(arr[2,:]) # printing the last row

[ 8  1 20]

In [ ]:
print(arr[1,2]) # printing the element in the second row third column

3

# Exercise 4

In [ ]:
np.sum(arr, axis = 0)

array([14, 23, 35])

In [113]:
np.mean(arr, axis = 1)

array([7.        , 7.33333333, 9.66666667])

# time to get into pandas

In [114]:
import pandas as pd

In [125]:
pd.DataFrame({
    "X": [True, False, True, True, False],
    "Y": [3.14, 7.65, 2.56, 7.89, 1.23],
    "Z": ["o", "a-", "b+", "b-", "o"]})

       X     Y   Z
0   True  3.14   o
1  False  7.65  a-
2   True  2.56  b+
3   True  7.89  b-
4  False  1.23   o

In [126]:
df = pd.read_csv('05_src/data/slides_data/bicycle_thefts_4326.csv')

In [122]:
# if we run into path issues,  run this code

import os
os.getcwd()

'/Users/mtp/Desktop/DSI/Sessions/Module2/python'

In [128]:
df

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,25565,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01T00:00:00,2015,April,Wednesday,1,91,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,May,Monday,16,137,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [129]:
df.dtypes

_id                        int64
OBJECTID                   int64
event_unique_id              str
Primary_Offence              str
Occurrence_Date              str
Occurrence_Year            int64
Occurrence_Month             str
Occurrence_DayOfWeek         str
Occurrence_DayOfMonth      int64
Occurrence_DayOfYear       int64
Occurrence_Hour            int64
Report_Date                  str
Report_Year                int64
Report_Month                 str
Report_DayOfWeek             str
Report_DayOfMonth          int64
Report_DayOfYear           int64
Report_Hour                int64
Division                     str
City                         str
Hood_ID                      str
NeighbourhoodName            str
Location_Type                str
Premises_Type                str
Bike_Make                    str
Bike_Model                   str
Bike_Type                    str
Bike_Speed                 int64
Bike_Colour                  str
Cost_of_Bike             float64
Status                       str
ObjectId2                  int64
geometry                     str
dtype: object

In [130]:
df.head

<bound method NDFrame.head of          _id  OBJECTID event_unique_id        Primary_Offence  \
0          1     17744  GO-20179016397            THEFT UNDER
1          2     17759  GO-20172033056  THEFT UNDER - BICYCLE
2          3     17906  GO-20189030822  THEFT UNDER - BICYCLE
3          4     17962   GO-2015804467            THEFT UNDER
4          5     17963  GO-20159002781            THEFT UNDER
...      ...       ...             ...                    ...
25564  25565      9361   GO-2015543181         MISCHIEF UNDER
25565  25566     11318  GO-20169004589            THEFT UNDER
25566  25567     11462  GO-20169005434            THEFT UNDER
25567  25568     11695  GO-20161170896            THEFT UNDER
25568  25569     11883  GO-20169007653  THEFT UNDER - BICYCLE

           Occurrence_Date  Occurrence_Year Occurrence_Month  \
0      2017-10-03T00:00:00             2017          October
1      2017-11-08T00:00:00             2017         November
2      2018-09-14T00:00:00             2018        September
3      2015-05-07T00:00:00             2015              May
4      2015-05-16T00:00:00             2015              May
...                    ...              ...              ...
25564  2015-04-01T00:00:00             2015            April
25565  2016-05-16T00:00:00             2016              May
25566  2016-06-04T00:00:00             2016             June
25567  2016-07-04T00:00:00             2016             July
25568  2016-07-22T00:00:00             2016             July

      Occurrence_DayOfWeek  Occurrence_DayOfMonth  Occurrence_DayOfYear  ...  \
0                  Tuesday                      3                   276  ...
1                Wednesday                      8                   312  ...
2                   Friday                     14                   257  ...
3                 Thursday                      7                   127  ...
4                 Saturday                     16                   136  ...
...                    ...                    ...                   ...  ...
25564            Wednesday                      1                    91  ...
25565               Monday                     16                   137  ...
25566             Saturday                      4                   156  ...
25567               Monday                      4                   186  ...
25568               Friday                     22                   204  ...

       Premises_Type     Bike_Make       Bike_Model Bike_Type Bike_Speed  \
0            Outside            GI         ESCAPE 2        OT          7
1              House  UNKNOWN MAKE              NaN        TO          1
2            Transit            OT       CROSSTRAIL        MT         24
3            Transit            GT              NaN        TO         10
4            Transit            GI              NaN        MT          6
...              ...           ...              ...       ...        ...
25564        Outside  UNKNOWN MAKE     BMX WILD MAN        RG          0
25565          House            SC              NaN        OT         14
25566      Apartment            SC           ANTRIM        MT         24
25567     Commercial  UNKNOWN MAKE              NaN        SC          1
25568        Outside            SU  ASCENT MOUNTAIN        MT         21

       Bike_Colour  Cost_of_Bike     Status ObjectId2  \
0              BLK         700.0     STOLEN         1
1              BLK        1100.0  RECOVERED         2
2              BLK         904.0     STOLEN         3
3           BLKDGR         400.0     STOLEN         4
4              RED         600.0     STOLEN         5
...            ...           ...        ...       ...
25564          SIL         600.0     STOLEN     25565
25565          NaN         900.0     STOLEN     25566
25566          WHI         700.0     STOLEN     25567
25567          NaN        3000.0     STOLEN     25568
25568          ONG         200.0     STOLEN     25569

                                                geometry
0      {'type': 'Point', 'coordinates': (-79.50655965...
1      {'type': 'Point', 'coordinates': (-79.50484874...
2      {'type': 'Point', 'coordinates': (-79.51170915...
3      {'type': 'Point', 'coordinates': (-79.51170915...
4      {'type': 'Point', 'coordinates': (-79.51132657...
...                                                  ...
25564  {'type': 'Point', 'coordinates': (-79.21555349...
25565  {'type': 'Point', 'coordinates': (-79.21767046...
25566  {'type': 'Point', 'coordinates': (-79.2360175,...
25567  {'type': 'Point', 'coordinates': (-79.20060719...
25568  {'type': 'Point', 'coordinates': (-79.23734742...

[25569 rows x 33 columns]>

In [132]:
df.tail (n=3)

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [135]:
df["Status"].unique()

<StringArray>
['STOLEN', 'RECOVERED', 'UNKNOWN']
Length: 3, dtype: str

In [136]:
df["Status"].value_counts()

Status
STOLEN       24807
UNKNOWN        454
RECOVERED      308
Name: count, dtype: int64

In [137]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   OBJECTID               25569 non-null  int64
 2   event_unique_id        25569 non-null  str
 3   Primary_Offence        25569 non-null  str
 4   Occurrence_Date        25569 non-null  str
 5   Occurrence_Year        25569 non-null  int64
 6   Occurrence_Month       25569 non-null  str
 7   Occurrence_DayOfWeek   25569 non-null  str
 8   Occurrence_DayOfMonth  25569 non-null  int64
 9   Occurrence_DayOfYear   25569 non-null  int64
 10  Occurrence_Hour        25569 non-null  int64
 11  Report_Date            25569 non-null  str
 12  Report_Year            25569 non-null  int64
 13  Report_Month           25569 non-null  str
 14  Report_DayOfWeek       25569 non-null  str
 15  Report_DayOfMonth      25569 non-null  int64
 16  Report_DayOfYear       25569 non-null  int64
 17  Report_Hour            25569 non-null  int64
 18  Division               25569 non-null  str
 19  City                   25569 non-null  str
 20  Hood_ID                25569 non-null  str
 21  NeighbourhoodName      25569 non-null  str
 22  Location_Type          25569 non-null  str
 23  Premises_Type          25569 non-null  str
 24  Bike_Make              25448 non-null  str
 25  Bike_Model             15923 non-null  str
 26  Bike_Type              25569 non-null  str
 27  Bike_Speed             25569 non-null  int64
 28  Bike_Colour            23508 non-null  str
 29  Cost_of_Bike           23825 non-null  float64
 30  Status                 25569 non-null  str
 31  ObjectId2              25569 non-null  int64
 32  geometry               25569 non-null  str
dtypes: float64(1), int64(12), str(20)
memory usage: 6.4 MB

In [138]:
df["Status"] = df["Status"].astype("category")

In [139]:
df.describe(include= "all")

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
count,25569.000000,25569.000000,25569,25569,25569,25569.000000,25569,25569,25569.000000,25569.000000,...,25569,25448,15923,25569,25569.000000,23508,23825.000000,25569,25569.000000,25569
unique,NaN,NaN,22771,66,2501,NaN,12,7,NaN,NaN,...,7,820,8097,13,NaN,252,NaN,3,NaN,5816
top,NaN,NaN,GO-20201550944,THEFT UNDER,2018-08-15T00:00:00,NaN,July,Friday,NaN,NaN,...,Outside,OT,UNKNOWN,MT,NaN,BLK,NaN,STOLEN,NaN,"{'type': 'Point', 'coordinates': (-79.38372586..."
freq,NaN,NaN,14,11904,39,NaN,4002,3924,NaN,NaN,...,7960,4991,304,8245,NaN,7422,NaN,24807,NaN,167
mean,12785.000000,12909.173218,NaN,NaN,NaN,2017.124174,NaN,NaN,15.616684,202.227698,...,NaN,NaN,NaN,NaN,14.164144,NaN,949.542371,NaN,12785.000000,NaN
std,7381.278853,7448.318562,NaN,NaN,NaN,1.960127,NaN,NaN,8.592886,76.821431,...,NaN,NaN,NaN,NaN,10.559215,NaN,1675.880345,NaN,7381.278853,NaN
min,1.000000,1.000000,NaN,NaN,NaN,2009.000000,NaN,NaN,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000,NaN
25%,6393.000000,6456.000000,NaN,NaN,NaN,2016.000000,NaN,NaN,8.000000,153.000000,...,NaN,NaN,NaN,NaN,6.000000,NaN,350.000000,NaN,6393.000000,NaN
50%,12785.000000,12918.000000,NaN,NaN,NaN,2017.000000,NaN,NaN,16.000000,205.000000,...,NaN,NaN,NaN,NaN,15.000000,NaN,600.000000,NaN,12785.000000,NaN
75%,19177.000000,19360.000000,NaN,NaN,NaN,2019.000000,NaN,NaN,23.000000,259.000000,...,NaN,NaN,NaN,NaN,21.000000,NaN,1000.000000,NaN,19177.000000,NaN
max,25569.000000,25806.000000,NaN,NaN,NaN,2020.000000,NaN,NaN,31.000000,366.000000,...,NaN,NaN,NaN,NaN,99.000000,NaN,120000.000000,NaN,25569.000000,NaN

In [140]:
df = df.drop(columns = "_id")

In [141]:
df.describe (include = "all")

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
count,25569.000000,25569,25569,25569,25569.000000,25569,25569,25569.000000,25569.000000,25569.000000,...,25569,25448,15923,25569,25569.000000,23508,23825.000000,25569,25569.000000,25569
unique,NaN,22771,66,2501,NaN,12,7,NaN,NaN,NaN,...,7,820,8097,13,NaN,252,NaN,3,NaN,5816
top,NaN,GO-20201550944,THEFT UNDER,2018-08-15T00:00:00,NaN,July,Friday,NaN,NaN,NaN,...,Outside,OT,UNKNOWN,MT,NaN,BLK,NaN,STOLEN,NaN,"{'type': 'Point', 'coordinates': (-79.38372586..."
freq,NaN,14,11904,39,NaN,4002,3924,NaN,NaN,NaN,...,7960,4991,304,8245,NaN,7422,NaN,24807,NaN,167
mean,12909.173218,NaN,NaN,NaN,2017.124174,NaN,NaN,15.616684,202.227698,13.274395,...,NaN,NaN,NaN,NaN,14.164144,NaN,949.542371,NaN,12785.000000,NaN
std,7448.318562,NaN,NaN,NaN,1.960127,NaN,NaN,8.592886,76.821431,6.530181,...,NaN,NaN,NaN,NaN,10.559215,NaN,1675.880345,NaN,7381.278853,NaN
min,1.000000,NaN,NaN,NaN,2009.000000,NaN,NaN,1.000000,1.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000,NaN
25%,6456.000000,NaN,NaN,NaN,2016.000000,NaN,NaN,8.000000,153.000000,9.000000,...,NaN,NaN,NaN,NaN,6.000000,NaN,350.000000,NaN,6393.000000,NaN
50%,12918.000000,NaN,NaN,NaN,2017.000000,NaN,NaN,16.000000,205.000000,14.000000,...,NaN,NaN,NaN,NaN,15.000000,NaN,600.000000,NaN,12785.000000,NaN
75%,19360.000000,NaN,NaN,NaN,2019.000000,NaN,NaN,23.000000,259.000000,19.000000,...,NaN,NaN,NaN,NaN,21.000000,NaN,1000.000000,NaN,19177.000000,NaN
max,25806.000000,NaN,NaN,NaN,2020.000000,NaN,NaN,31.000000,366.000000,23.000000,...,NaN,NaN,NaN,NaN,99.000000,NaN,120000.000000,NaN,25569.000000,NaN

In [143]:
df["Occurrence_Month"] = df["Occurrence_Month"][:3]

In [144]:
df.loc[df["Bike_Model"].isna()]

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,3,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
3,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,NaN,Thursday,7,127,18,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,NaN,Saturday,16,136,12,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
7,20993,GO-2019819460,THEFT UNDER,2019-05-01T00:00:00,2019,NaN,Wednesday,1,121,13,...,Transit,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965..."
8,21209,GO-20179014159,THEFT UNDER,2017-09-06T00:00:00,2017,NaN,Wednesday,6,249,8,...,Transit,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,9046,GO-20149007555,THEFT UNDER,2014-10-03T00:00:00,2014,NaN,Friday,3,276,21,...,Other,UK,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795..."
25562,9083,GO-20143134832,THEFT UNDER,2014-10-17T00:00:00,2014,NaN,Friday,17,290,17,...,House,SUPERCYCLE,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678..."
25563,9155,GO-20143239833,THEFT UNDER,2014-11-04T00:00:00,2014,NaN,Tuesday,4,308,19,...,Outside,CHEROKEE,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103..."
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,NaN,Monday,16,137,21,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,NaN,Monday,4,186,20,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."

In [146]:
models_to_keep = ["HYBRID", "SIRRUS", "ESCAPE"] #filter using Loc

df.loc[df["Bike_Model"].isin(models_to_keep)]

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
87,21080,GO-20191970007,B&E,2019-10-11T00:00:00,2019,NaN,Friday,11,284,22,...,Other,SPECIALIZED,SIRRUS,TO,21,BLKBLU,950.0,STOLEN,87,"{'type': 'Point', 'coordinates': (-79.48640535..."
228,1135,GO-20179012278,THEFT UNDER - BICYCLE,2017-08-05T00:00:00,2017,NaN,Saturday,5,217,23,...,Apartment,TR,HYBRID,OT,8,BLK,2000.0,STOLEN,224,"{'type': 'Point', 'coordinates': (-79.48678673..."
257,2748,GO-20189021105,THEFT UNDER - BICYCLE,2018-07-02T00:00:00,2018,NaN,Monday,2,183,12,...,Outside,OT,HYBRID,MT,15,WHI,1800.0,STOLEN,253,"{'type': 'Point', 'coordinates': (-79.48323001..."
730,17860,GO-20189023474,THEFT UNDER - BICYCLE,2018-07-20T00:00:00,2018,NaN,Friday,20,201,1,...,Outside,GI,ESCAPE,OT,65,GRY,650.0,STOLEN,723,"{'type': 'Point', 'coordinates': (-79.48760733..."
899,21345,GO-20181755711,B&E,2018-09-21T00:00:00,2018,NaN,Friday,21,264,1,...,Commercial,SPECIALIZED,SIRRUS,OT,0,BLU,500.0,STOLEN,890,"{'type': 'Point', 'coordinates': (-79.53250412..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24346,21564,GO-20201306023,THEFT UNDER - BICYCLE,2020-05-01T00:00:00,2020,NaN,Friday,1,122,0,...,Other,SPECIALIZED,SIRRUS,RG,24,BLK,1300.0,STOLEN,24334,"{'type': 'Point', 'coordinates': (-79.41826195..."
24733,1718,GO-20171919540,THEFT UNDER - BICYCLE,2017-10-17T00:00:00,2017,NaN,Tuesday,17,290,23,...,House,UNKNOWN MAKE,HYBRID,TO,10,BLK,700.0,UNKNOWN,24721,"{'type': 'Point', 'coordinates': (-79.23103567..."
24916,4856,GO-20199023501,THEFT UNDER,2019-07-22T00:00:00,2019,NaN,Monday,22,203,20,...,House,GI,ESCAPE,OT,21,BLK,400.0,STOLEN,24904,"{'type': 'Point', 'coordinates': (-79.2826472,..."
24998,9803,GO-20159003602,THEFT UNDER,2015-06-14T00:00:00,2015,NaN,Sunday,14,165,8,...,House,OT,SIRRUS,MT,18,BLK,800.0,STOLEN,24988,"{'type': 'Point', 'coordinates': (-79.26689373..."
25014,6793,GO-20201407793,THEFT UNDER - BICYCLE,2020-06-11T00:00:00,2020,NaN,Thursday,11,163,17,...,Outside,GIANT,ESCAPE,TO,18,GRY,600.0,STOLEN,25004,"{'type': 'Point', 'coordinates': (-79.21309175..."

In [149]:
df["Bike_Model"] = (df["Bike_Model"].str.replace("a'","a"))

In [150]:
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,14,...,Outside,GI,ESCaPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,3,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,9,...,Transit,OT,CROSSTRaIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,NaN,Thursday,7,127,18,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,NaN,Saturday,16,136,12,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01T00:00:00,2015,NaN,Wednesday,1,91,17,...,Outside,UNKNOWN MAKE,BMX WILD MaN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,NaN,Monday,16,137,21,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,NaN,Saturday,4,156,22,...,Apartment,SC,aNTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,NaN,Monday,4,186,20,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,NaN,Friday,22,204,9,...,Outside,SU,aSCENT MOUNTaIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [151]:
model_groups = df.groupby("Bike_Model")

In [152]:
model_groups["Bike_Make"].unique()

Bike_Model
#199-2763-0                  [SU]
&BaCK SaDDLEBaG              [GI]
'11 7.2 FX WSD               [TR]
'INTENSE""         [UNKNOWN MAKE]
'PIRaNHa'                    [GF]
                        ...
aXIS5                        [OT]
aXIa                         [NO]
aZ EBIKE           [UNKNOWN MAKE]
aa00302619                   [NO]
aa10851515                   [NO]
Name: Bike_Make, Length: 8097, dtype: object

In [153]:
df.to_csv("updated_df.csv")

# pandas exercise 1

In [154]:
pf = pd.read_csv('05_src/data/slides_data/subway_stations.csv')

In [155]:
pf.head()

    stop_lat   stop_lon            station
0  43.666061 -79.411065   BATHURST STATION
1  43.670149 -79.390089        BAY STATION
2  43.766872 -79.386703    BAYVIEW STATION
3  43.769202 -79.376312  BESSARION STATION
4  43.670049 -79.385389      BLOOR STATION

In [156]:
pf.tail(n=2)

     stop_lat   stop_lon             station
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

In [157]:
pf.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stop_lat  77 non-null     float64
 1   stop_lon  77 non-null     float64
 2   station   77 non-null     str
dtypes: float64(2), str(1)
memory usage: 1.9 KB

In [163]:
stations_to_keep = ["COLLEGE STATION", "ROYAL YORK STATION"] #filter using Loc

pf.loc[pf["station"].isin(stations_to_keep)]

     stop_lat   stop_lon             station
9   43.660149 -79.382688     COLLEGE STATION
54  43.648338 -79.511178  ROYAL YORK STATION

In [164]:
pf.to_csv("exported_data.csv")